### ISSUE TITLE
New Release with updated RELEASE files?

### ISSUE THREAD

**Issue by jwlodek** [areaDetector/ADMerlin#14]
I was compiling ADMerlin on both Debian 8 and Ubuntu 18.04 LTS machines, and I ran into an issue where the following error was displayed multiple times:
```
EPICS/Release.pm: Undefined macro $(SUPPORT) used 
```
and the build would fail. I saw the same problem with ADAndor3, but when I tried ADProsilica I had no issues, so my top level `configure/` should be ok. I found that I had to edit the two RELEASE files within ADMerlin and ADAndor3 in `configure/RELEASE` and `iocs/merlinIOC/configure` replacing the lines:
```
-include $(TOP)/../../../configure/RELEASE_PATHS.local
-include $(TOP)/../../../configure/RELEASE_PATHS.local.$(EPICS_HOST_ARCH)
-include $(TOP)/../../../configure/RELEASE_PRODS.local
-include $(TOP)/RELEASE.local
-include $(TOP)/configure/RELEASE.local
```
with the following:
```
-include $(TOP)/../../../configure/RELEASE_PRODS_INCLUDE
-include $(TOP)/RELEASE.local
-include $(TOP)/configure/RELEASE.local
```
It seems that the problem was that I was building ADMerlin from the latest release, which doesn't have these updated files. Is there any chance that there will be a new Release tag of ADMerlin and ADAndor3 that include these updated files? I can simply build from master for now, but We prefer to build strict releases, so that we can identify the exact sources that were built without having to find the original build location.

**Comment by MarkRivers** [comment]
There have been many changes since the v4.0 release, including changing the names of many files and directories.  I have updated the RELEASE.md for R4-1.  I can tag it, or perhaps we can get @gilesknap to take a look and do it.

**Comment by jwlodek** [comment]
Thank you that would be great. We are using scripts to build areaDetector and package binaries into a tarball, and we would like to include a release version for each driver, so we can know where the binary came from.

**Comment by gilesknap** [comment]
@jwlodek I'll be able to take a look at this on Monday.

**Comment by gilesknap** [comment]
I've made a release - I now need to untangle our local repo master and dls-master since there have been some DLS-specific commits to the master branch.
