### ISSUE TITLE
Problem building ADMerlin

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADMerlin#2]
We have the Merlin detector on loan from Quantum Detectors for a couple of weeks.  The detector is running and collecting reasonable images, and I can talk to it over telnet.  Note that the manual was wrong, it says the command port is 6341 and the data port is 6342, but it is actually the opposite.

In order to be useful I need to put the LabView system in the hutch and run it from outside the hutch.  That means I need to run the EPICS areaDetector IOC.  I would like to do that on my Linux machine.
I just pulled the latest code from github. However, when I try to build ADMerlin I run into problems.  It appears that this driver is quite old.  ADMerlin/configure/RELEASE contains the following lines, for example:

```
SUPPORT=/dls_sw/prod/R3.14.11/support
WORK=/dls_sw/work/R3.14.11/support
ASYN =         $(SUPPORT)/asyn/4-21
AREADETECTOR = $(SUPPORT)/areaDetector/1-9dls12
```

So it appears to be built with areaDetector 1-9, not 2-X. 
There is an iocs/ directory, but it only contains a Makefile.
Is there a more recent version available, that will build with areaDetector 2-4?

**Comment by mdmoo1978** [comment]
Mark,

I did do most of the updates need to make it 2-x compliant during my time
at APS. You can get to it at https://github.com/mdmoo1978/ADMerlin. I'm not
sure if everything is completely correct in that repository, but the
detector pool as a build of the driver and IOC that should work.

I didn't do a pull because of some difference between Diamond's needs and
ours.

Matt

**Comment by gilesknap** [comment]
I am scheduled to be doing some work on this driver in the next couple of months and will do the update to 2-x then.

**Comment by MarkRivers** [comment]
Thanks @mdmoo1978 and @gilesknap.  I will start with Matt's version.  Hopefully we can do a pull request to get a version that is compliant with the normal areaDetector 2-x framework into the official version soon.

**Comment by MarkRivers** [comment]
Hi Matt,

I downloaded your repository.

Here are the problems I have found:

The top-level Makefile contains the line:
DIRS := $(DIRS) merlinApp
But there is no merlinApp, there is only medipixApp.

When I build in medipixApp it fails because of this line:

medipixDetector_LIBS += cbfad

Where is libcbfad.a supposed to be found?

The top-level iocs/ directory only contains a Makefile, so how did you build an application?

Thanks,
Mark

**Comment by MarkRivers** [comment]
Hi Matt,

I downloaded your repository.

Here are the problems I have found:

The top-level Makefile contains the line:
DIRS := $(DIRS) merlinApp
But there is no merlinApp, there is only medipixApp.

When I build in medipixApp it fails because of this line:

medipixDetector_LIBS += cbfad

Where is libcbfad.a supposed to be found?

The top-level iocs/ directory only contains a Makefile, so how did you build an application?

Thanks,
Mark

**Comment by mdmoo1978** [comment]
Mark,

I can't really help you, I don't have access to the built system.

Matt

**Comment by MarkRivers** [comment]
Hi Matt,
I just want to be sure I understand the situation.  Was there a working Merlin IOC in the detector pool, and the problem is just that the working code was not pushed back to github?  The code on github definitely could not have worked, there are basic problems like the name of the directory being wrong, no files in the iocs/ directory, etc.   If so, should the detector pool folks be able to find that code on one of their computers?

Thanks,
Mark

**Comment by mdmoo1978** [comment]
Yes, I have had multiple systems run the Merlin IOC. 

Matthew D. Moore
(585) 303-5474

**Comment by MarkRivers** [comment]
Hi Matt,

If you were able to log in to the detector pool computers do you think you would be able to find the most recent version of your driver?  Perhaps they could get you temporary access.

Mark

**Comment by MarkRivers** [comment]
Russell found an ADMerlin directory on one of the DP computers.  He said it is where Matt told him to look.  The merlinApp directory looks OK, and I was able to build it.

However, the iocs/iocBoot directory only contains iocProsilica and iocProsilica-DP,  which are still set up for the Prosilica, not for the Merlin.  This cannot be the tree that was actually used to talk to the Merlin.  It is also not a git repository, there is no .git file in that tree.

I expect I will be able to create a working version, but it would save time if we could find the directory Matt was actually working in.

Mark

From: Mark Rivers
Sent: Tuesday, March 08, 2016 2:03 PM
To: 'areaDetector/ADMerlin'; areaDetector/ADMerlin
Cc: 'Woods, Russell'; 'Antonino Miceli'
Subject: RE: [ADMerlin] Problem building ADMerlin (#2)

Hi Matt,

If you were able to log in to the detector pool computers do you think you would be able to find the most recent version of your driver?  Perhaps they could get you temporary access.

Mark

**Comment by MarkRivers** [comment]
It looked like the “crap” directory was a working iocboot directory, at least for the Merlin Quad

From: Mark Rivers [mailto:rivers@cars.uchicago.edu]
Sent: Tuesday, March 08, 2016 5:00 PM
To: 'areaDetector/ADMerlin' reply@reply.github.com; 'areaDetector/ADMerlin' ADMerlin@noreply.github.com
Cc: Woods, Russell rwoods@aps.anl.gov; Miceli, Antonino amiceli@aps.anl.gov
Subject: RE: [ADMerlin] Problem building ADMerlin (#2)

Russell found an ADMerlin directory on one of the DP computers.  He said it is where Matt told him to look.  The merlinApp directory looks OK, and I was able to build it.

However, the iocs/iocBoot directory only contains iocProsilica and iocProsilica-DP,  which are still set up for the Prosilica, not for the Merlin.  This cannot be the tree that was actually used to talk to the Merlin.  It is also not a git repository, there is no .git file in that tree.

I expect I will be able to create a working version, but it would save time if we could find the directory Matt was actually working in.

Mark

From: Mark Rivers
Sent: Tuesday, March 08, 2016 2:03 PM
To: 'areaDetector/ADMerlin'; areaDetector/ADMerlin
Cc: 'Woods, Russell'; 'Antonino Miceli'
Subject: RE: [ADMerlin] Problem building ADMerlin (#2)

Hi Matt,

If you were able to log in to the detector pool computers do you think you would be able to find the most recent version of your driver?  Perhaps they could get you temporary access.

Mark

**Comment by MarkRivers** [comment]
We found Matt Moore's code on the APS detector pool computer.  I am using that as the starting point for a new branch in this repository.  I am closing this issue and opening a new one.
